"use client"

import localFont from "next/font/local";
import "../app/styles/layout.css"
import { useRouter } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const navigateHome = ()=>{
    router.push("/home")
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className="navbar-main">
        <div className="left-nav">
            <img src="/logo.jpg" alt="logo" className="app-logo"></img>
            <h1 className="app-name">R.R Governance</h1>
        </div>
        <div className="right-nav">
            <button className="nav-buttons" onClick={navigateHome}>Home</button>
            
            <div className="dropdown">
                <button className="nav-buttons dropdown-button">
                    Forms
                    <span>   </span>
                    <span className="dropdown-icon">▼</span>
                </button>
                <div className="dropdown-content">
                    <a href="CheckIn">Check In Form</a>
                    <a href="NewEntry">New Entry Form</a>
                    <a href="#form3">Form 3</a>
                </div>
            </div>
            
            <div className="dropdown">
                <button className="nav-buttons dropdown-button">
                    Reports
                    <span>   </span>
                    <span className="dropdown-icon">▼</span>
                </button>
                <div className="dropdown-content">
                    <a href="#report1">Report 1</a>
                    <a href="#report2">Report 2</a>
                    <a href="#report3">Report 3</a>
                </div>
            </div>
            
            <button className="nav-buttons">About Us</button>
        </div>
    </div>
        {children}
      </body>
    </html>
  );
}
